---
- name: Test
  hosts: localhost
  become: true
#  connection: ssh
  gather_facts: false

  tasks:
    - raw: hostname
      register: test

    - debug: 
        var: test


#  roles:
#    - lab_openstack
