---
- name: End to end smoke tests
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ groups.database_servers[0] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.backend_servers[0] }}"
      run_once: true
