---
# tasks file for roles/lab_satellite
- name: In-Memory Inventory
  os_server_info:
    cloud: "{{ guid }}-project"
  register: instances

- name: Build In-Memory inventory
  add_host:
    host: "{{ instance.name }}.{{ internal_domain }}"
    group: "{{ instance.metadata.AnsibleGroup }}"
    ansible_host: "{{ instance.private_v4 }}"
    ssh_private_key_file: "{{ home }}/.ssh/{{ guid }}key.pem"
  when: instance.metadata.AnsibleGroup == "osp_instances"
  loop: "{{ instances.openstack_servers }}"
  loop_control:
    loop_var: instance

- name: Display
  debug:
    var: groups

- name: install katello-ca-consumer package
  yum:
    name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
    disable_gpg_check: true

- name: register system and attach subs
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activationkey }}"
    org_id: "{{ satellite_org }}"
    auto_attach: true
